### ISSUE TITLE
problem with powermate.exe

### ISSUE THREAD

**Issue by Flynns82** [EsotericSoftware/powermate#3]
Hi, i have a problem with this software, my powermate work only when the powermate.jar is running, but when i try to start powermate.exe nothing appear, the only powermate.exe that start is the original file provided from the ufficial website(obv it cannot configure device). what i can try to solve? thanks

**Comment by NathanSweet** [comment]
powermate.exe tries to find your system Java installation, then runs the JAR. You can just run the JAR yourself, it's the same.

**Comment by Flynns82** [comment]
I'm using the .jar currently, so I can only go to adjust the volume from the powermate, but I have no way of configuring it, if I open powermate.exe, nothing is opened

**Comment by NathanSweet** [comment]
Configure what?

**Comment by Flynns82** [comment]
all the command, if i press, if i rotate etc..

**Comment by NathanSweet** [comment]
This app controls the volume only. If you want to do anything else, you'll need to write Java code for that. Probably if this app has the USB device open, other apps cannot also control the device.

FWIW, I stopped using my Powermate because Griffon has poor APIs and poor software support, especially on Windows. Their wireless knob doesn't work on Windows at all.
